version: '3.8'

services:
  db:
    image: postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 'postgres'
      POSTGRES_DB: productsservice
    volumes:
      - './productsdata/:/var/lib/postgresql/data'
    ports:
      - '5432:5432'
        
  server: 
    build: ./
    ports:
      - '80:3000'
    depends_on:
      - db

volumes:
  productsdata: